CREATE TABLE `places` (
 `id` INT auto_increment NOT NULL,
 `name` varchar(255) NOT NULL,
 `description` varchar(255) NOT NULL,
 `rating` double NOT NULL,
 PRIMARY KEY (`id`)
)

insert into `places` (`name`, `description`, `rating`) values
(`Aroma Mocha`, `Beautiful place with perfect interior`, 5.6),
(`Baristas`, `Beautiful place with perfect interior`, 6.6),
(`Beans ''n Cream Cafe`, `Beautiful place with perfect interior`, 8.3),
(`Beany Business`, `Beautiful place with perfect interior`, 4.6),
(`Boston Barista`, `Beautiful place with perfect interior`, 3.8),
(`Club Coffee`, `Beautiful place with perfect interior`, 2.9),
(`Coffee Express`, `Beautiful place with perfect interior`, 9.0),
(`Coffee House`, `Beautiful place with perfect interior`, 5.5),
(`Coffee Time`, `Beautiful place with perfect interior`, 5.6),
(`Cup o'' Joe`, `Beautiful place with perfect interior`, 8.6),
(`Dream Bean Coffee Shop`, `Beautiful place with perfect interior`, 4.8),
(`Espresso Cafe`, `Beautiful place with perfect interior`, 9.6),
(`Espresso Express`, `Beautiful place with perfect interior`, 10.0),
(`Expresso`, `Beautiful place with perfect interior`, 7.7),
(`Grind House`, `Beautiful place with perfect interior`, 5.6),
(`Aroma Mocha`, `Beautiful place with perfect interior`, 5.6),
(`Baristas`, `Beautiful place with perfect interior`, 6.6),
(`Beans ''n Cream Cafe`, `Beautiful place with perfect interior`, 8.3),
(`Beany Business`, `Beautiful place with perfect interior`, 4.6),
(`Boston Barista`, `Beautiful place with perfect interior`, 3.8),
(`Club Coffee`, `Beautiful place with perfect interior`, 2.9),
(`Coffee Express`, `Beautiful place with perfect interior`, 9.0),
(`Coffee House`, `Beautiful place with perfect interior`, 5.5),
(`Coffee Time`, `Beautiful place with perfect interior`, 5.6),
(`Cup o'' Joe`, `Beautiful place with perfect interior`, 8.6),
(`Dream Bean Coffee Shop`, `Beautiful place with perfect interior`, 4.8),
(`Espresso Cafe`, `Beautiful place with perfect interior`, 9.6),
(`Espresso Express`, `Beautiful place with perfect interior`, 10.0),
(`Expresso`, `Beautiful place with perfect interior`, 7.7),
(`Grind House`, `Beautiful place with perfect interior`, 5.6);

